// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuitionCalculator_WebApp.Models.DataLayer;

#nullable disable

namespace TuitionCalculator_WebApp.Migrations
{
    [DbContext(typeof(CollegeCostContext))]
    partial class CollegeCostContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TuitionCalculator_WebApp.Models.CollegeCost", b =>
                {
                    b.Property<int>("CollegeCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostOfBooks")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostOfHousing")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPerCreditHour")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditHoursPerTerm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsToGraduate")
                        .HasColumnType("INTEGER");

                    b.HasKey("CollegeCostId");

                    b.ToTable("CollegeCost");
                });
#pragma warning restore 612, 618
        }
    }
}
